    --Prueba de la asignacion de fechas para cada vacuna
    
    DBMS_OUTPUT.PUT_LINE('sputnik');
        DBMS_OUTPUT.PUT_LINE('fase I -> ' || fechas_sputnik.fecha_f1);
        DBMS_OUTPUT.PUT_LINE('fase II -> ' || fechas_sputnik.fecha_f2);
        DBMS_OUTPUT.PUT_LINE('fase III -> ' || fechas_sputnik.fecha_f3);
        DBMS_OUTPUT.PUT_LINE('fase IV -> ' || fechas_sputnik.fecha_f4);
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('pfizer');
        DBMS_OUTPUT.PUT_LINE('fase I -> ' || fechas_pfizer.fecha_f1);
        DBMS_OUTPUT.PUT_LINE('fase II -> ' || fechas_pfizer.fecha_f2);
        DBMS_OUTPUT.PUT_LINE('fase III -> ' || fechas_pfizer.fecha_f3);
        DBMS_OUTPUT.PUT_LINE('fase IV -> ' || fechas_pfizer.fecha_f4);
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('moderna');
        DBMS_OUTPUT.PUT_LINE('fase I -> ' || fechas_moderna.fecha_f1);
        DBMS_OUTPUT.PUT_LINE('fase II -> ' || fechas_moderna.fecha_f2);
        DBMS_OUTPUT.PUT_LINE('fase III -> ' || fechas_moderna.fecha_f3);
        DBMS_OUTPUT.PUT_LINE('fase IV -> ' || fechas_moderna.fecha_f4);
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('sinopharm');
        DBMS_OUTPUT.PUT_LINE('fase I -> ' || fechas_sinopharm.fecha_f1);
        DBMS_OUTPUT.PUT_LINE('fase II -> ' || fechas_sinopharm.fecha_f2);
        DBMS_OUTPUT.PUT_LINE('fase III -> ' || fechas_sinopharm.fecha_f3);
        DBMS_OUTPUT.PUT_LINE('fase IV -> ' || fechas_sinopharm.fecha_f4);
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------'); 
    DBMS_OUTPUT.PUT_LINE('sinovac');
        DBMS_OUTPUT.PUT_LINE('fase I -> ' || fechas_sinovac.fecha_f1);
        DBMS_OUTPUT.PUT_LINE('fase II -> ' || fechas_sinovac.fecha_f2);
        DBMS_OUTPUT.PUT_LINE('fase III -> ' || fechas_sinovac.fecha_f3);
        DBMS_OUTPUT.PUT_LINE('fase IV -> ' || fechas_sinovac.fecha_f4);
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------');  
    DBMS_OUTPUT.PUT_LINE('cansino');
        DBMS_OUTPUT.PUT_LINE('fase I -> ' || fechas_cansino.fecha_f1);
        DBMS_OUTPUT.PUT_LINE('fase II -> ' || fechas_cansino.fecha_f2);
        DBMS_OUTPUT.PUT_LINE('fase III -> ' || fechas_cansino.fecha_f3);
        DBMS_OUTPUT.PUT_LINE('fase IV -> ' || fechas_cansino.fecha_f4);
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------'); 
    DBMS_OUTPUT.PUT_LINE('aztrazeneca');
        DBMS_OUTPUT.PUT_LINE('fase I -> ' || fechas_aztrazeneca.fecha_f1);
        DBMS_OUTPUT.PUT_LINE('fase II -> ' || fechas_aztrazeneca.fecha_f2);
        DBMS_OUTPUT.PUT_LINE('fase III -> ' || fechas_aztrazeneca.fecha_f3);
        DBMS_OUTPUT.PUT_LINE('fase IV -> ' || fechas_aztrazeneca.fecha_f4);
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------'); 
    DBMS_OUTPUT.PUT_LINE('J and J');
        DBMS_OUTPUT.PUT_LINE('fase I -> ' || fechas_JANDJ.fecha_f1);
        DBMS_OUTPUT.PUT_LINE('fase II -> ' || fechas_JANDJ.fecha_f2);
        DBMS_OUTPUT.PUT_LINE('fase III -> ' || fechas_JANDJ.fecha_f3);
        DBMS_OUTPUT.PUT_LINE('fase IV -> ' || fechas_JANDJ.fecha_f4);
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------'); 
    DBMS_OUTPUT.PUT_LINE('janssen');
        DBMS_OUTPUT.PUT_LINE('fase I -> ' || fechas_janssen.fecha_f1);
        DBMS_OUTPUT.PUT_LINE('fase II -> ' || fechas_janssen.fecha_f2);
        DBMS_OUTPUT.PUT_LINE('fase III -> ' || fechas_janssen.fecha_f3);
        DBMS_OUTPUT.PUT_LINE('fase IV -> ' || fechas_janssen.fecha_f4);
    DBMS_OUTPUT.PUT_LINE('---------------------------------------------'); 