CREATE OR REPLACE FUNCTION covax_existe RETURN BOOLEAN IS 

    covax_id DISTRIBUIDORA.id_dist%TYPE;
BEGIN
    SELECT id_dist INTO covax_id FROM DISTRIBUIDORA 
    WHERE nombre_dist = 'COVAX';
    EXCEPTION WHEN NO_DATA_FOUND THEN 
    RETURN (FALSE);
    
    RETURN (TRUE);
END;
/