CREATE OR REPLACE FUNCTION covax_existe RETURN BOOLEAN IS 

        var DISTRIBUIDORA.id_dist%TYPE;
BEGIN
    SELECT id_dist INTO var FROM DISTRIBUIDORA 
    WHERE nombre_dist = 'COVAX';
    EXCEPTION WHEN NO_DATA_FOUND THEN 
    RETURN (FALSE);
    
    RETURN (TRUE);
END;
/