--TABLA PAIS 

--C
INSERT INTO JORGE.PAIS VALUES (DEFAULT,DEFAULT,'prueba','AME',0,'N',1,1);

--R
SELECT * FROM JORGE.PAIS;

--U
UPDATE JORGE.PAIS SET nombre_pai = 'alemania' WHERE id_pai = (SELECT MAX(id_pai) FROM JORGE.PAIS);

--D
DELETE FROM JORGE.PAIS WHERE id_pai = (SELECT MAX(id_pai) FROM JORGE.PAIS);




--TABLA CENTRO VACUNACION

--C
INSERT INTO JORGE.CENTRO_VAC VALUES (DEFAULT,'prueba',0,1,JORGE.UBICACION(JORGE.UBICACION.validarLatitud(10.472838636319286),JORGE.UBICACION.validarLongitud(-66.89428693533952),'prueba'));

--R
SELECT * FROM JORGE.CENTRO_VAC;

--U
UPDATE JORGE.CENTRO_VAC SET nombre_cen = 'prueba2' WHERE id_cen = (SELECT MAX(id_cen) FROM JORGE.CENTRO_VAC);

--D
DELETE FROM JORGE.CENTRO_VAC WHERE id_cen = (SELECT MAX(id_cen) FROM JORGE.CENTRO_VAC);




--TABLA INVENTARIO VACUNA

--C
INSERT INTO JORGE.INVENTARIO_VAC VALUES ((SELECT MAX(id_cen) FROM JORGE.CENTRO_VAC),1,0,0);

--R
SELECT * FROM JORGE.INVENTARIO_VAC;

--U
UPDATE JORGE.INVENTARIO_VAC SET cantidad_pri_inv = 999 WHERE centro_vac_inv = (SELECT MAX(id_cen) FROM JORGE.CENTRO_VAC);

--D
DELETE FROM JORGE.INVENTARIO_VAC WHERE centro_vac_inv = (SELECT MAX(id_cen) FROM JORGE.CENTRO_VAC);




--TABLA JORNADA VACUNA

--C
INSERT INTO JORGE.JORNADA_VAC VALUES (TO_DATE('22/10/1999','dd/mm/yyyy'),1,1,1,1,1,1);

--R
SELECT * FROM JORGE.JORNADA_VAC ORDER BY fecha_jv;

--U
UPDATE JORGE.JORNADA_VAC SET cantidad_pri_JV = 999 WHERE fecha_jv = TO_DATE('22/10/1999','dd/mm/yyyy');

--D
DELETE FROM JORGE.JORNADA_VAC WHERE fecha_jv = TO_DATE('22/10/1999','dd/mm/yyyy');




--TABLA JV_EFEC

--C
INSERT INTO JORGE.JORNADA_VAC VALUES (TO_DATE('22/10/1999','dd/mm/yyyy'),1,1,1,1,1,1);--jornada para probar
INSERT INTO JORGE.JV_EFEC VALUES (0,1,1,TO_DATE('22/10/1999','dd/mm/yyyy'),1,1,1);

--R
SELECT * FROM JORGE.JV_EFEC ORDER BY fecha_jve;

--U
UPDATE JORGE.JV_EFEC SET cantidad_efsec_jv = 999 WHERE fecha_jve = TO_DATE('22/10/1999','dd/mm/yyyy');

--D
DELETE FROM JORGE.JV_EFEC WHERE fecha_jve = TO_DATE('22/10/1999','dd/mm/yyyy');




--TABLA SUMINISTROS

--C
INSERT INTO JORGE.SUMINISTROS VALUES(TO_DATE('22/10/1999','dd/mm/yyyy'),1,0,0,0,0);

--R
SELECT * FROM JORGE.SUMINISTROS ORDER BY fecha_sum;

--U
UPDATE JORGE.SUMINISTROS SET cant_jeringas_sum = 999 WHERE fecha_sum = TO_DATE('22/10/1999','dd/mm/yyyy');

--D
DELETE FROM JORGE.SUMINISTROS WHERE fecha_sum = TO_DATE('22/10/1999','dd/mm/yyyy');




--TABLA VACUNA

--C
INSERT INTO JORGE.VACUNA VALUES(DEFAULT,'prueba',0,0,0,0,'N',0,'',JORGE.f_fases(NULL,NULL,NULL,NULL));

--R
SELECT * FROM JORGE.VACUNA;

--U
UPDATE JORGE.VACUNA SET precio_vac  = 999 WHERE id_vac = (SELECT MAX(id_vac) FROM JORGE.VACUNA);

--D
DELETE FROM JORGE.VACUNA WHERE id_vac = (SELECT MAX(id_vac) FROM JORGE.VACUNA);




--TABLA EFECTO SECUNDARIO

--C
INSERT INTO JORGE.EFECTO_SECUNDARIO VALUES (DEFAULT,'prueba', ' ',0);

--R
SELECT * FROM JORGE.EFECTO_SECUNDARIO;

--U
UPDATE JORGE.EFECTO_SECUNDARIO SET nombre_efe  = 'prueba2' WHERE id_efe = (SELECT MAX(id_efe) FROM JORGE.EFECTO_SECUNDARIO);

--D
DELETE FROM JORGE.EFECTO_SECUNDARIO WHERE id_efe = (SELECT MAX(id_efe) FROM JORGE.EFECTO_SECUNDARIO);




--TABLA VAC_EFEC

--C
INSERT INTO JORGE.VAC_EFEC VALUES (4,1);

--R
SELECT * FROM JORGE.VAC_EFEC;

--U
UPDATE JORGE.VAC_EFEC SET efecto_secundario_ve  = 2 WHERE efecto_secundario_ve  = 4 AND vacuna_ve = 1;

--D
DELETE FROM JORGE.VAC_EFEC WHERE (efecto_secundario_ve  = 2 OR efecto_secundario_ve = 4) AND vacuna_ve = 1;


ROLLBACK;