--TABLA PAIS 

--C
INSERT INTO JORGE.PAIS VALUES (DEFAULT,DEFAULT,'prueba','AME',0,'N',1,1);

--R
SELECT * FROM JORGE.PAIS;

--U
UPDATE JORGE.PAIS SET nombre_pai = 'alemania' WHERE id_pai = (SELECT MAX(id_pai) FROM JORGE.PAIS);

--D
DELETE FROM JORGE.PAIS WHERE id_pai = (SELECT MAX(id_pai) FROM JORGE.PAIS);




--TABLA CENTRO VACUNACION

--C
INSERT INTO JORGE.CENTRO_VAC VALUES (DEFAULT,'prueba',0,1,JORGE.UBICACION(JORGE.UBICACION.validarLatitud(10.472838636319286),JORGE.UBICACION.validarLongitud(-66.89428693533952),'prueba'));

--R
SELECT * FROM JORGE.CENTRO_VAC;

--U
UPDATE JORGE.CENTRO_VAC SET nombre_cen = 'prueba2' WHERE id_cen = (SELECT MAX(id_cen) FROM JORGE.CENTRO_VAC);

--D
DELETE FROM JORGE.CENTRO_VAC WHERE id_cen = (SELECT MAX(id_cen) FROM JORGE.CENTRO_VAC);




--TABLA INVENTARIO VACUNA

--C
INSERT INTO JORGE.INVENTARIO_VAC VALUES ((SELECT MAX(id_cen) FROM JORGE.CENTRO_VAC),1,0,0);

--R
SELECT * FROM JORGE.INVENTARIO_VAC;

--U
UPDATE JORGE.INVENTARIO_VAC SET cantidad_pri_inv = 999 WHERE centro_vac_inv = (SELECT MAX(id_cen) FROM JORGE.CENTRO_VAC);

--D
DELETE FROM JORGE.INVENTARIO_VAC WHERE centro_vac_inv = (SELECT MAX(id_cen) FROM JORGE.CENTRO_VAC);




--TABLA JORNADA VACUNA

--C
INSERT INTO JORGE.JORNADA_VAC VALUES (TO_DATE('22/10/1999','dd/mm/yyyy'),1,1,1,1,1,1);

--R
SELECT * FROM JORGE.JORNADA_VAC ORDER BY fecha_jv;

--U
UPDATE JORGE.JORNADA_VAC SET cantidad_pri_JV = 999 WHERE fecha_jv = TO_DATE('22/10/1999','dd/mm/yyyy');

--D
DELETE FROM JORGE.JORNADA_VAC WHERE fecha_jv = TO_DATE('22/10/1999','dd/mm/yyyy');

ROLLBACK;