CREATE OR REPLACE PROCEDURE creacion_covax IS

    DECLARE
        VACUNAS CURSOR;
        REGISTRO_VAC VACUNA%ROWTYPE;
        COVAX_ID DISTRIBUIDORA.id_dist%TYPE;
BEGIN

    INSERT INTO DISTRIBUIDORA VALUES (DEFAULT, 'COVAX');    --INSERT DE COVAX EN LA TABLA DISTRIBUIDORA
    SELECT id_dist INTO COVAX_ID FROM DISTRIBUIDORA 
    WHERE nombre_dist = 'COVAX';
    VACUNAS := get_vacunas;
    OPEN VACUNAS;
    FETCH VACUNAS INTO REGISTRO_VAC;
    WHILE VACUNAS%FOUND
        LOOP 
            if (REGISTRO_VAC.covax_vac = 'Y') THEN
            INSERT INTO VACUNA_DISTRIBUIDORA VALUES (REGISTRO_VAC.id_vac, COVAX_ID, 0);      --ASIGNACION DE CADA VACUNA A COVAX CON CANTIDAD 0 (EN OTRO PROCEDURE SE ASIGNARA EL 30% DE CADA VACUNA EN EL MOMENTO QUE LLEGUE A FASE 4)
            end if;
        END LOOP;
    CLOSE VACUNAS;  
    DBMS_OUTPUT.PUT_LINE('Se conformo la alianza COVAX.');
END;